#ifndef MCD_PROTOCOL_H
#define MCD_PROTOCOL_H
#define MCD_ABI_VERSION 0x0100
#define MCD_READY_MAGIC 0x4D43
#define MCD_CMD_READ 1
#define MCD_CMD_PREPARE_ADPCM 2
#define MCD_CMD_PLAY_ADPCM 3
#define MCD_CMD_STOP_ADPCM 4
#define MCD_CMD_PLAY_CDDA 5
#define MCD_CMD_STOP_CDDA 6
#define MCD_CMD_PAUSE_CDDA 7
#define MCD_CMD_RESUME_CDDA 8
#define MCD_ASSET_BOOT 0
#define MCD_ASSET_IMAGE 1
#define MCD_ASSET_AUDIO 2
#define MCD_ASSET_MISSING 3
#define MCD_OK 0
#define MCD_ERR_ARGUMENT 1
#define MCD_ERR_NOT_FOUND 2
#define MCD_ERR_READ 3
#define MCD_ERR_FORMAT 4
#define MCD_ERR_TIMEOUT 5
#define MCD_ERR_NOT_READY 6
#define MCD_ERR_BUSY 7
#define MCD_ERR_SIZE 8
#define MCD_AUDIO_READY 1
#define MCD_AUDIO_PLAYING 2
#define MCD_CDDA_REQUESTED 4
#define MCD_CDDA_PAUSED 8
#endif
